copyright: © 2014 AOSC. Articles are released under GFDL license.
title:
    en: AOSC Big News
    zh: AOSC 搞的大新闻
brief:
    en: Too young too simple
    zh: Lorem ipsum dolor sit amet
author: Joy Neop
year: 2014
multiLang: [en,zh]